# Generated by Django 5.0.3 on 2025-07-29 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_otp_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_created_at',
        ),
    ]
