# Generated by Django 5.2.3 on 2025-08-28 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_actress_user_image_user_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='actress',
            new_name='permanent_address',
        ),
    ]
