# Generated by Django 5.2.3 on 2026-02-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='savings_goal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
